#!/usr/bin/env python3
"""Refresh compact README metadata from pyproject.toml; standard library only.

The pre-commit hook and Depot call this script. --activity remains accepted for
older automation; activity, backlog and command help now stay at their sources.
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
START, END = "<!-- BAZAAR:STATUS:START -->", "<!-- BAZAAR:STATUS:END -->"


def render(readme: str) -> str:
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]
    commands = ", ".join(f"`{name}`" for name in sorted(project["scripts"]))
    block = "\n".join(
        [
            START,
            "<!-- Generated by scripts/readme_status.py from pyproject.toml. -->",
            f"Python `{project['requires-python']}` · CLI entry points: {commands}.",
            END,
        ]
    )
    # ponytail: one bounded metadata block; detailed inventories belong in their source docs.
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)
    if readme.count(START) != 1 or readme.count(END) != 1 or not pattern.search(readme):
        raise SystemExit("README.md must contain exactly one ordered status block")
    return pattern.sub(lambda _: block, readme)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the metadata is stale")
    parser.add_argument("--activity", action="store_true", help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    current = README.read_text(encoding="utf-8")
    updated = render(current)
    if args.check:
        if updated != current:
            print("README.md metadata is stale: run python3 scripts/readme_status.py", file=sys.stderr)
            return 1
        return 0
    if updated != current:
        README.write_text(updated, encoding="utf-8")
        print("README.md metadata updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
