#!/usr/bin/env python3
"""Regenerate the auto-maintained status block in README.md. Standard library only.

Sources (the block changes only when one of them changes, so teammates' branches rarely clash):
  - .ai/specs/02-plan.md   -> "Task index" table
  - src/bazaar_agent/cli.py -> every `bazaar` command with its one-line help
  - .ai/memory.md          -> the latest log entry headings
Run by .githooks/pre-commit.d/10-readme-status. `--check` exits 1 when README is stale.
On a merge conflict inside the block: resolve either way, then rerun this script.
"""

from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
START, END = "<!-- BAZAAR:STATUS:START -->", "<!-- BAZAAR:STATUS:END -->"
# Rewritten only by CI on main (.github/workflows/readme.yml): branches never touch it, so no conflicts.
ACT_START, ACT_END = "<!-- BAZAAR:ACTIVITY:START -->", "<!-- BAZAAR:ACTIVITY:END -->"
ACTIVITY_MERGES = 12
MEMORY_ENTRIES = 8


def task_index() -> str:
    plan = (ROOT / ".ai/specs/02-plan.md").read_text(encoding="utf-8")
    match = re.search(r"## Task index\n\n(\|.*?)\n\n", plan, re.S)
    return match.group(1).strip() if match else "_No task index in .ai/specs/02-plan.md._"


def _command_name(decorator: ast.expr, func: ast.FunctionDef) -> tuple[str, str] | None:
    if not (isinstance(decorator, ast.Call) and isinstance(decorator.func, ast.Attribute)):
        return None
    if decorator.func.attr != "command" or not isinstance(decorator.func.value, ast.Name):
        return None
    group = {
        "app": "",
        "feed_app": "feed ",
        "db_app": "db ",
        "dealer_app": "dealer ",
        "duel_app": "duel ",
        "rules_app": "rules ",
        "obs_app": "obs ",
        "sell_app": "sell ",
    }.get(decorator.func.value.id)
    if group is None:
        return None
    explicit = decorator.args[0].value if decorator.args and isinstance(decorator.args[0], ast.Constant) else None
    return group, str(explicit or func.name.replace("_", "-"))


def cli_commands() -> str:
    cli = ROOT / "src/bazaar_agent/cli.py"
    if not cli.is_file():
        return "_No CLI on this branch yet._"
    tree = ast.parse(cli.read_text(encoding="utf-8"))
    rows = []
    for node in tree.body:
        if not isinstance(node, ast.FunctionDef):
            continue
        for decorator in node.decorator_list:
            found = _command_name(decorator, node)
            if found:
                group, name = found
                doc = (ast.get_docstring(node) or "").splitlines()[0] if ast.get_docstring(node) else ""
                rows.append(f"| `uv run bazaar {group}{name}` | {doc} |")
    return "| Command | What it does |\n|---|---|\n" + "\n".join(rows)


def memory_entries() -> str:
    path = ROOT / ".ai/memory.md"
    if not path.is_file():
        return "_No .ai/memory.md yet._"
    heads = [line[4:].strip() for line in path.read_text(encoding="utf-8").splitlines() if line.startswith("### [")]
    if not heads:
        return "_No entries yet._"
    return "\n".join(f"- {h}" for h in heads[-MEMORY_ENTRIES:][::-1])


def block() -> str:
    return "\n".join(
        [
            START,
            "<!-- Generated by scripts/readme_status.py on every commit. Do not edit by hand. -->",
            "",
            "### Backlog (from `.ai/specs/02-plan.md`)",
            "",
            task_index(),
            "",
            "### CLI commands (from `src/bazaar_agent/cli.py`)",
            "",
            cli_commands(),
            "",
            "### Latest team memory (from `.ai/memory.md`, newest first)",
            "",
            memory_entries(),
            "",
            END,
        ]
    )


def _run(*cmd: str) -> str:
    import subprocess

    try:
        return subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, timeout=30, check=True).stdout
    except (OSError, subprocess.SubprocessError):
        return ""


def recent_merges() -> str:
    log = _run(
        "git",
        "log",
        "--merges",
        "--first-parent",
        "-n",
        str(ACTIVITY_MERGES),
        "--format=%h%x09%ad%x09%s",
        "--date=format:%a %H:%M",
    )
    rows = []
    for line in log.splitlines():
        sha, when, subject = (line.split("\t") + ["", ""])[:3]
        m = re.match(r"Merge pull request #(\d+) from \S+", subject)
        title = ""
        if m:
            title = _run("git", "log", "-1", "--format=%b", sha).strip().splitlines()[0:1]
            title = title[0] if title else ""
            rows.append(f"| [#{m[1]}](../../pull/{m[1]}) | {title} | {when} | `{sha}` |")
    return "| PR | Title | Merged | Commit |\n|---|---|---|---|\n" + "\n".join(rows) if rows else "_No merges yet._"


def open_prs() -> str:
    import json

    raw = _run("gh", "pr", "list", "--state", "open", "--json", "number,title,headRefName,isDraft", "--limit", "20")
    try:
        prs = json.loads(raw) if raw else []
    except ValueError:
        prs = []
    if not prs:
        return "_No open PRs (or `gh` unavailable)._"
    rows = [f"| [#{p['number']}](../../pull/{p['number']}) | {p['title']} | `{p['headRefName']}` |" for p in prs]
    return "| PR | Title | Branch |\n|---|---|---|\n" + "\n".join(rows)


def activity_block() -> str:
    return "\n".join(
        [
            ACT_START,
            "<!-- Generated by CI on every push to main (.github/workflows/readme.yml). Do not edit by hand. -->",
            "",
            "### Recently merged",
            "",
            recent_merges(),
            "",
            "### Open pull requests",
            "",
            open_prs(),
            "",
            ACT_END,
        ]
    )


def render_activity(readme: str) -> str:
    pattern = re.compile(re.escape(ACT_START) + r".*?" + re.escape(ACT_END), re.S)
    if not pattern.search(readme):
        return readme
    return pattern.sub(lambda _: activity_block(), readme)


def render(readme: str) -> str:
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)
    if not pattern.search(readme):
        raise SystemExit(f"README.md has no {START} … {END} block")
    return pattern.sub(lambda _: block(), readme)


def main(argv: list[str]) -> int:
    current = README.read_text(encoding="utf-8")
    updated = render(current)
    if "--activity" in argv:  # CI only: also refresh merges and open PRs
        updated = render_activity(updated)
    if "--check" in argv:
        if updated != current:
            print("README.md status block is stale: run python3 scripts/readme_status.py", file=sys.stderr)
            return 1
        return 0
    if updated != current:
        README.write_text(updated, encoding="utf-8")
        print("README.md status block updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
